FROM openjdk:11

RUN apt-get update && apt-get install -y git maven

ARG TOKEN

WORKDIR /app

RUN git clone https://github.com/mis3003/currency-exchange.git && \
    cd currency-exchange && \
    mvn package

CMD ["bash"]